export const EVIDENCE_STATUS = Object.freeze({
  VERIFIED_OFFICIAL: 'VERIFIED_OFFICIAL',
  OFFICIAL_PENDING_REVIEW: 'OFFICIAL_PENDING_REVIEW',
  SUPERSEDED: 'SUPERSEDED',
  WITHDRAWN: 'WITHDRAWN',
});

export const CURRENT_STATE = Object.freeze({
  CURRENT: 'CURRENT',
  SUPERSEDED: 'SUPERSEDED',
  WITHDRAWN: 'WITHDRAWN',
  UNRESOLVED: 'UNRESOLVED',
});

export const MATERIAL_TYPE = Object.freeze({
  FULL_TEXT: 'FULL_TEXT',
  SUPPLIED_EXCERPT: 'SUPPLIED_EXCERPT',
  SYNTHETIC_FIXTURE: 'SYNTHETIC_FIXTURE',
});

export const EXECUTION_MODE = Object.freeze({
  NORMAL: 'NORMAL',
  SYNTHETIC_ACCEPTANCE: 'SYNTHETIC_ACCEPTANCE',
});

export const JURISDICTION_RELATION = Object.freeze({
  MATCH: 'MATCH',
  OUTSIDE: 'OUTSIDE',
  UNKNOWN: 'UNKNOWN',
});

export const ELIGIBILITY = Object.freeze({
  ELIGIBLE_INTERNAL_DRAFT: 'ELIGIBLE_INTERNAL_DRAFT',
  REVIEW_ONLY: 'REVIEW_ONLY',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
});

export const RELEVANCE = Object.freeze({
  RELEVANT: 'RELEVANT',
  POSSIBLY_RELEVANT: 'POSSIBLY_RELEVANT',
  NOT_RELEVANT: 'NOT_RELEVANT',
  UNKNOWN: 'UNKNOWN',
});

export const IMPACT_LEVEL = Object.freeze({
  INFO: 'INFO',
  CHECK: 'CHECK',
  ACTION_REQUIRED: 'ACTION_REQUIRED',
  URGENT_REVIEW: 'URGENT_REVIEW',
});

export const SIGNAL_KIND = Object.freeze({
  FACT: 'FACT',
  CHANGE: 'CHANGE',
  OBLIGATION: 'OBLIGATION',
  DEADLINE: 'DEADLINE',
  URGENCY: 'URGENCY',
});

export const DRAFT_REVIEW_STATUS = 'NOT_REVIEWED';
export const PUBLICATION_AUTHORIZATION = 'NOT_AUTHORIZED';

export const UNCERTAINTY = Object.freeze({
  EVIDENCE_NOT_VERIFIED: 'EVIDENCE_NOT_VERIFIED',
  EFFECTIVE_DATE_UNKNOWN: 'EFFECTIVE_DATE_UNKNOWN',
  RELEVANCE_UNCERTAIN: 'RELEVANCE_UNCERTAIN',
  OBLIGATION_UNCONFIRMED: 'OBLIGATION_UNCONFIRMED',
  SUPERSESSION_UNRESOLVED: 'SUPERSESSION_UNRESOLVED',
  MATERIAL_UNAVAILABLE: 'MATERIAL_UNAVAILABLE',
  MATERIAL_MISMATCH: 'MATERIAL_MISMATCH',
  CURRENT_STATE_CONFLICT: 'CURRENT_STATE_CONFLICT',
  JURISDICTION_UNKNOWN: 'JURISDICTION_UNKNOWN',
  SOURCE_FACT_UNAVAILABLE: 'SOURCE_FACT_UNAVAILABLE',
});

export class SliceBValidationError extends Error {
  constructor(code, issues = []) {
    super(code);
    this.name = 'SliceBValidationError';
    this.code = code;
    this.issues = Object.freeze([...issues]);
  }
}
